### ISSUE TITLE
Feature : Retain Board State

### ISSUE THREAD

**Issue by aaditya-paul** [Sreyasree-001/DrawLive#2]
While developing the retain board state feature the undo and redo feature could be done as well.

**Comment by Sreyasree-001** [comment]
Would you like to work on it? 
@aaditya-paul

**Comment by aaditya-paul** [comment]
> Would you like to work on it? 
> @aaditya-paul 

Ypp i would definitely like to work on this project. Would you mind sharing any of your socials where we could discuss abt it.

**Comment by Sreyasree-001** [comment]
> > Would you like to work on it?
> > @aaditya-paul
> 
> Ypp i would definitely like to work on this project. Would you mind sharing any of your socials where we could discuss abt it.

Sure, we can connect on Linkedin. Here is my profile link [https://www.linkedin.com/in/sreyasree-sasmal-a5274324b/]
